name: Build and Publish to PyPI

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    environment: 
      name: 'production'
      url: '${{ steps.deploy.outputs.url }}'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: package
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

